# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cca8fcc82ec2e7871cb8209d6ce8c1c5fa71af9fd7fb15164670a23c9388ca0a8a5575d21842b73d82da9739700a0adb744e62832e50e4dea8cc579f6fa09a6

test:
  secret_key_base: 76e7a87ef94876f2ff3dbf9b75f697eaed483a34fd2870787595c84895565851f05936e2ae42d6e518019f04ecccb59a06aebdfe1afcee9aaf082a39f9f485bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
